package com.zh.test.mapper;

import com.zh.test.pojo.TestUser;

import java.util.List;


public interface TestUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbggenerated Thu Nov 10 19:00:02 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbggenerated Thu Nov 10 19:00:02 CST 2022
     */
    int insert(TestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbggenerated Thu Nov 10 19:00:02 CST 2022
     */
    int insertSelective(TestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbggenerated Thu Nov 10 19:00:02 CST 2022
     */
    TestUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbggenerated Thu Nov 10 19:00:02 CST 2022
     */
    int updateByPrimaryKeySelective(TestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_user
     *
     * @mbggenerated Thu Nov 10 19:00:02 CST 2022
     */
    int updateByPrimaryKey(TestUser record);

    List<TestUser> selectByName(String name);

}